### ISSUE TITLE
Foundation 6 Plugins and JS dependant

### ISSUE THREAD

**Issue by bioduds** [nerijunior/meteor-foundation6#1]
Hello!
Thanks for the Foundation 6 package for Meteor! Works pronto! One issue I am having is to be able to add plugins and JS dependencies on it. For instance, the accordion from Foundation 6. Can you please help me?

thanks

**Comment by nerijunior** [comment]
@bioduds I did this package only to use the basic of Foundation 6 but if you want to use the foundation plugins I really recommend to use it [zurb/foundation-sites](https://atmospherejs.com/zurb/foundation-sites).

I hope that helps!

**Comment by bioduds** [comment]
Então, eu tentei o foundation-sites, deu erro na instalação do package. Se
vc descobrir depois como usar o seu e conseguir usar os plugins, me avisa
por favor ou coloca lá no README do package no atmosphere.

Mto obrigado!!

abs
